import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { redis } from "~/redis";
import { toast } from "react-hot-toast";
import Router from "next/router";
interface Info {
  img_url: string;
  title: string;
}
const Home: NextPage = () => {

  async function getURL() {
    const r = await redis.mget("img_url", "title");
    // console.log("🎇🧨🎐🎃", r[0], r[1])
    setR({ img_url: r[0] as string, title: r[1] as string });
  }
  useEffect(() => {
    getURL();
  }, []);

  const [input, setInput] = useState<string>("");
  const [title, setTitle] = useState<string>("");
  const [r, setR] = useState<Info>({ img_url: "", title: "" });
  async function handle(event: FormEvent) {
    event.preventDefault();
    const data = {
      img_url: input,
      title: title,
    };
    // console.log(JSON.stringify(data))
    const rs = await fetch("/api/redis", {
      method: "POST",
      body: JSON.stringify(data),
    });
    if (rs.status !== 200) {
      toast.error("failed to post to redis");
      throw new Error("failed to post to redis");
    }
    console.log(JSON.stringify(input));
    toast.success("image url updated successfully");
    setInput("");
    setTitle("");
    Router.reload();
  }
  return (
    <>
      <Head>
        <title>Twitter Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="flex w-full max-w-xl p-1">
          <form action="" onSubmit={handle} className="w-full space-y-2">
            <input
              type="url"
              id="tweet"
              required
              value={input}
              className="w-full flex-grow rounded-lg border-4 border-slate-400 bg-transparent p-4 text-xl outline-none "
              placeholder="http://img-url.com/"
              onChange={(e) => setInput(e.target.value)}
              autoComplete="off"
            />
            <input
              type="text"
              id="title"
              required
              maxLength={30}
              value={title}
              className="w-full flex-grow rounded-lg border-4 border-slate-400 bg-transparent p-4 text-xl outline-none "
              placeholder="like ?"
              onChange={(e) => setTitle(e.target.value)}
              autoComplete="off"
            />
            <button
              type="submit"
              className="mb-2 mr-2 rounded-lg border border-gray-800 px-5 py-2.5 text-center text-sm font-medium text-gray-900 hover:bg-gray-900 hover:text-white focus:outline-none focus:ring-4 focus:ring-gray-300 dark:border-gray-600 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white dark:focus:ring-gray-800"
            >
              submit
            </button>
          </form>
        </div>
        <div className="h-4" />
        <div className="flex space-x-5 ">
          <Link
            className="text-blue-700 hover:text-blue-500 md:font-sans md:text-xl md:font-semibold "
            href="/"
          >
            Back to home{" "}
          </Link>
          <Link
            className="text-blue-700 hover:text-blue-500 md:font-sans md:text-xl md:font-semibold "
            href={r.img_url}
            target="_blank"
          >
            Link to image{" "}
          </Link>
          <a className="md:font-sans md:text-lg md:font-normal ">
            {r.title}
          </a>
        </div>
      </main>
    </>
  );
};

export default Home;
