import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FormEvent, useState } from "react";
const Home: NextPage = () => {
  const [input, setInput] = useState<string>("");
  async function handle(event: FormEvent) {
    event.preventDefault();
    const data = {
      img_url: input,
    };
    const rs = await fetch("/api/redis", {
      method: "POST",
      body: JSON.stringify(data),
    });
    if (!rs.ok ) throw new Error("failed to post to redis")
    console.log(JSON.stringify(input));
    setInput("");
  }
  return (
    <>
      <Head>
        <title>Twitter Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="mb-5">
          <label
            htmlFor="image url"
            className="block text-sm font-medium leading-6 text-gray-900"
          >
            Image url
          </label>
          <div className="relative mt-2 flex space-x-3 rounded-md shadow-sm">
            <form action="" onSubmit={handle} className="w-full">
              <input
                type="url"
                required
                name="input"
                id="input"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                autoComplete="off"
                className="block w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                placeholder="http://img-url.com/"
              />
            </form>
          </div>
        </div>
        <Link href="/">Back to home </Link>
      </main>
    </>
  );
};

export default Home;
