import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
const Home: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>Twitter Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Link className="text-slate-200 text-4xl font-sans" href="/createRedis">create Image url </Link>
      </main>
    </>
  );
};

export default Home;
